idf_component_register(
    SRCS 
        "main.c" 
        "buttons.c"
        "menu.c" 
        "lcd.c"
        "analizator.c"
        "cooling.c"
    INCLUDE_DIRS 
        "."
    REQUIRES 
        driver 
        esp_adc 
        led_strip 
        GP1247AI 
        ds18b20 
        animation
        espressif__esp-dsp
        esp_timer
)