idf_component_register(
    SRCS
        "main.c"
        "lcd.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        freertos
        log
        esp_adc
        led_strip
        DS18b20
        GP1247AI
        ADAU
        AK_DRIVERS
        i2c_bus
        analizator
        APP_UI
        ANIMATIONS
)